# ✅ Name of the Workflow
name: Pipeline CI/CD frontend-app

# ✅ Trigger this workflow on push to main branch
on:
  push:
    branches:
      - main

# ✅ Global Environment Variables
 

jobs:
  # ✅ Run Unit Tests
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone Source Code
        uses: actions/checkoutactions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run:  npm i
      
      - name: run unit test
        run: npm run test 

   
       
    